version: "3.3"
services:
  wealth_build:
    image: wealth_build:latest
    build: .
    ports:
    - "8080:8080"

    environment:
      slavko: value123456789
      spring_datasource_url: jdbc:postgresql://db:5432/postgres

    deploy:
      replicas: 1

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
    - postgres:/data/postgres
    ports:
    - "5432:5432"
#    networks:
#    - postgres

volumes:
  postgres:
#networks:
#  postgres:
